export const ADD_PLACE = 'ADD_PLACE';
export const REMOVE_PLACE = 'REMOVE_PLACE';
export const SET_SELECTED_PLACE = 'SET_SELECTED_PLACE';

export const ADD_KEYWORD = 'ADD_KEYWORD';
export const REMOVE_KEYWORD = 'REMOVE_KEYWORD';
export const SET_SELECTED_KEYWORD = 'SET_SELECTED_KEYWORD';
